#!/bin/sh
set -eu

if [ -z "${APPDIR:-}" ]; then
  APPDIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
  export APPDIR
fi

if [ -n "${LD_LIBRARY_PATH:-}" ]; then
  LD_LIBRARY_PATH="${APPDIR}/usr/lib:${LD_LIBRARY_PATH}"
else
  LD_LIBRARY_PATH="${APPDIR}/usr/lib"
fi
export LD_LIBRARY_PATH

exec "${APPDIR}/usr/bin/ymir-helga" "$@"
